// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoHBSIS.Models;

namespace ProjetoHBSIS.Migrations
{
    [DbContext(typeof(ProjetoHBSISContext))]
    [Migration("20190523023752_BDHouse")]
    partial class BDHouse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoHBSIS.Models.Contribuinte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("NumeroDepentedentes");

                    b.Property<double>("RendaBrutaMensal");

                    b.HasKey("Id");

                    b.ToTable("Contribuinte");
                });

            modelBuilder.Entity("ProjetoHBSIS.Models.ImpostodeRenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContribuinteId");

                    b.Property<int>("SalarioMinimoId");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ContribuinteId")
                        .IsUnique();

                    b.HasIndex("SalarioMinimoId");

                    b.ToTable("ImpostodeRenda");
                });

            modelBuilder.Entity("ProjetoHBSIS.Models.SalarioMinimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ano")
                        .IsRequired();

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.ToTable("SalarioMinimo");
                });

            modelBuilder.Entity("ProjetoHBSIS.Models.ImpostodeRenda", b =>
                {
                    b.HasOne("ProjetoHBSIS.Models.Contribuinte", "Contribuinte")
                        .WithOne("ImpostodeRenda")
                        .HasForeignKey("ProjetoHBSIS.Models.ImpostodeRenda", "ContribuinteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjetoHBSIS.Models.SalarioMinimo", "SalarioMinimo")
                        .WithMany()
                        .HasForeignKey("SalarioMinimoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
