// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoHBSIS.Models;

namespace ProjetoHBSIS.Migrations
{
    [DbContext(typeof(ProjetoHBSISContext))]
    [Migration("20190522221854_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoHBSIS.Models.Contribuinte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeroDepentedentes");

                    b.Property<double>("RendaBrutaMensal");

                    b.HasKey("Id");

                    b.ToTable("Contribuinte");
                });
#pragma warning restore 612, 618
        }
    }
}
